use crate::auth::commands::validate_auth_path;
use crate::auth::store::CredentialStore;
use crate::auth::store::open_private_directory;
use crate::daemon;
use crate::state::SyncState;
use clap::Subcommand;
use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::{self, IsTerminal, Write};
use std::os::unix::fs::{DirBuilderExt, MetadataExt, OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process;
use std::sync::atomic::{AtomicU64, Ordering};
use thiserror::Error;

#[allow(dead_code)]
mod launchd;
#[allow(dead_code)]
mod systemd;
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
mod unsupported {
    use super::{ManagerStatus, ServiceError, ServiceSettings};
    use std::path::PathBuf;

    fn unsupported() -> ServiceError {
        ServiceError::Message(
            "service management is supported only on macOS launchd and Linux systemd --user".into(),
        )
    }

    pub(super) fn definition_path() -> Result<PathBuf, ServiceError> {
        Err(unsupported())
    }
    pub(super) fn render_definition(_: &ServiceSettings) -> Result<String, ServiceError> {
        Err(unsupported())
    }
    pub(super) fn status() -> Result<ManagerStatus, ServiceError> {
        Err(unsupported())
    }
    pub(super) fn install() -> Result<(), ServiceError> {
        Err(unsupported())
    }
    pub(super) fn start() -> Result<(), ServiceError> {
        Err(unsupported())
    }
    pub(super) fn stop() -> Result<(), ServiceError> {
        Err(unsupported())
    }
    pub(super) fn uninstall() -> Result<(), ServiceError> {
        Err(unsupported())
    }
    pub(super) fn reload() -> Result<(), ServiceError> {
        Err(unsupported())
    }
}

#[cfg(target_os = "macos")]
use launchd as platform;
#[cfg(target_os = "linux")]
use systemd as platform;
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
use unsupported as platform;

static TEMP_COUNTER: AtomicU64 = AtomicU64::new(0);
const SERVICE_MARKER: &str = "Managed by artifact-sync. Do not edit this file directly.";

#[derive(Debug, Subcommand)]
pub enum ServiceCommand {
    /// Register, enable, and start the per-user service
    Install {
        /// Confirm that existing artifacts may upload during startup
        #[arg(long)]
        yes: bool,
    },
    /// Show service-manager and local publishing health
    Status,
    /// Start an installed service
    Start {
        /// Confirm that existing artifacts may upload when the service starts
        #[arg(long)]
        yes: bool,
    },
    /// Stop an installed service without removing it
    Stop,
    /// Stop and unregister the service; credentials and sync state are preserved
    Uninstall,
}

#[derive(Debug, Error)]
pub enum ServiceError {
    #[error("{0}")]
    Message(String),
    #[error("service configuration I/O failed: {0}")]
    Io(#[from] io::Error),
    #[error("authentication configuration failed: {0}")]
    Store(#[from] crate::auth::store::StoreError),
}

#[derive(Debug, Clone)]
pub(super) struct ServiceSettings {
    pub executable: PathBuf,
    pub auth_config: PathBuf,
    pub publishing_config: PathBuf,
}

#[derive(Debug, Clone)]
pub(super) struct ManagerStatus {
    pub state: String,
    pub loaded: bool,
    pub active: bool,
    pub enabled: bool,
    pub process_id: Option<u32>,
    pub detail: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct SavedServiceSettings {
    managed_by: String,
    version: u8,
    auth_config: PathBuf,
    publishing_config: PathBuf,
}

pub async fn run(
    command: ServiceCommand,
    auth_path: PathBuf,
    publishing_path: PathBuf,
) -> Result<(), ServiceError> {
    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        let _ = (command, auth_path, publishing_path);
        return Err(ServiceError::Message(
            "service management is supported only on macOS launchd and Linux systemd --user".into(),
        ));
    }

    #[cfg(any(target_os = "macos", target_os = "linux"))]
    match command {
        ServiceCommand::Install { yes } => install(auth_path, publishing_path, yes).await,
        ServiceCommand::Status => status().await,
        ServiceCommand::Start { yes } => start(auth_path, publishing_path, yes).await,
        ServiceCommand::Stop => stop().await,
        ServiceCommand::Uninstall => uninstall().await,
    }
}

async fn install(
    auth_path: PathBuf,
    publishing_path: PathBuf,
    yes: bool,
) -> Result<(), ServiceError> {
    validate_auth_path(&auth_path, &publishing_path)
        .map_err(|error| ServiceError::Message(error.to_string()))?;
    let auth_file = CredentialStore::new(&auth_path).load()?;
    if auth_file
        .as_ref()
        .and_then(|file| file.auth.as_ref())
        .is_none()
    {
        return Err(ServiceError::Message(format!(
            "no saved credential at {}; run `artifact-sync login` before installing the service",
            auth_path.display()
        )));
    }

    let executable = fs::canonicalize(std::env::current_exe()?)?;
    if !fs::metadata(&executable)?.is_file() {
        return Err(ServiceError::Message(
            "current artifact-sync executable is not a regular file".into(),
        ));
    }
    let settings = ServiceSettings {
        executable,
        auth_config: fs::canonicalize(&auth_path)?,
        publishing_config: absolute_path(&publishing_path)?,
    };
    let definition_path = platform::definition_path()?;
    let existing_definition = owned_definition(&definition_path)?;
    if existing_definition {
        ensure_service_directory(
            definition_path
                .parent()
                .ok_or_else(|| ServiceError::Message("service definition has no parent".into()))?,
        )?;
    }
    let manager_status = platform::status()?;
    if manager_status.loaded && !existing_definition {
        return Err(ServiceError::Message(
            "the user service manager already has an artifact-sync service that is not managed by this CLI; inspect it and remove it manually before installing".into(),
        ));
    }
    let daemon_running = daemon::daemon_is_running().await?;
    let daemon_status = if daemon_running {
        daemon::query_status().await.unwrap_or(None)
    } else {
        None
    };
    let manager_owns_daemon = service_manager_owns_daemon(
        existing_definition,
        manager_status.active,
        manager_status.process_id,
        daemon_status.as_ref(),
    );
    if daemon_running && !manager_owns_daemon {
        return Err(ServiceError::Message(
            "an unmanaged artifact-sync daemon is already running; stop that `artifact-sync daemon` process before installing the service".into(),
        ));
    }

    let root = settings
        .publishing_config
        .parent()
        .ok_or_else(|| ServiceError::Message("publishing config has no parent".into()))?;
    let artifact_count = count_publishable_files(root, &settings.publishing_config)?;
    if artifact_count > 0 && !confirm_existing_artifact_uploads(artifact_count, yes, "install")? {
        println!("Service installation cancelled; no service files were changed.");
        return Ok(());
    }

    if existing_definition && manager_status.loaded {
        platform::stop()?;
    }
    write_managed_definition(&definition_path, &platform::render_definition(&settings)?)?;
    write_saved_settings(&settings)?;
    platform::install()?;
    println!("Installed and started the per-user artifact-sync service.");
    println!("Service definition: {}", definition_path.display());
    println!("Authentication file: {}", settings.auth_config.display());
    if artifact_count > 0 {
        println!("Existing artifacts will be reconciled and may upload.");
    }
    Ok(())
}

async fn status() -> Result<(), ServiceError> {
    let path = platform::definition_path()?;
    let installed = match owned_definition(&path) {
        Ok(installed) => installed,
        Err(error) => {
            println!("Service definition: conflict ({error})");
            false
        }
    };
    let manager = match platform::status() {
        Ok(status) => status,
        Err(error) => {
            println!("Service manager: unavailable ({error})");
            ManagerStatus {
                state: "unavailable".into(),
                loaded: false,
                active: false,
                enabled: false,
                process_id: None,
                detail: None,
            }
        }
    };
    println!(
        "Service definition: {}",
        if installed {
            "installed"
        } else {
            "not installed"
        }
    );
    println!("Service manager: {}", manager.state);
    println!("Service manager enabled: {}", manager.enabled);
    println!("Service manager active: {}", manager.active);
    if let Some(process_id) = manager.process_id {
        println!("Service PID: {process_id}");
    }
    if let Some(detail) = manager.detail {
        println!("Service manager detail: {detail}");
    }

    let mut pending_count_reported = false;
    match daemon::query_status().await {
        Ok(Some(status)) => {
            println!("Daemon: running");
            println!("Daemon PID: {}", status.process_id);
            println!("Publishing: {}", status.publishing_state.as_str());
            println!("Artifact root: {}", status.artifact_root);
            if let Some(team) = status.team {
                let verification = if status.identity_verified {
                    "verified this run"
                } else {
                    "not verified this run"
                };
                println!("Team: {team} ({verification})");
            }
            if let Some(source) = status.credential_source {
                println!("Credential source: {source}");
            }
            println!("Pending uploads: {}", status.pending_count);
            pending_count_reported = true;
        }
        Ok(None) => match daemon::daemon_is_running().await {
            Ok(true) => {
                println!("Daemon: running; status protocol is unavailable in this daemon version");
            }
            Ok(false) => println!("Daemon: not running"),
            Err(error) => println!("Daemon status unavailable: {error}"),
        },
        Err(error) => println!("Daemon status unavailable: {error}"),
    }
    if !pending_count_reported {
        match SyncState::pending_count_default() {
            Ok(count) => println!("Pending uploads: {count}"),
            Err(error) => println!("Pending uploads unavailable: {error}"),
        }
    }
    Ok(())
}

async fn start(
    auth_path: PathBuf,
    publishing_path: PathBuf,
    yes: bool,
) -> Result<(), ServiceError> {
    if !require_owned_definition()? {
        return Err(ServiceError::Message(
            "artifact-sync service is not installed; run `artifact-sync service install` first"
                .into(),
        ));
    }
    let settings = load_saved_settings()?;
    if absolute_path(&auth_path)? != settings.auth_config
        || absolute_path(&publishing_path)? != settings.publishing_config
    {
        return Err(ServiceError::Message(format!(
            "this service was installed with auth config {} and publishing config {}; pass those same paths to `service start`",
            settings.auth_config.display(),
            settings.publishing_config.display()
        )));
    }
    let auth_file = CredentialStore::new(&settings.auth_config).load()?;
    if auth_file
        .as_ref()
        .and_then(|file| file.auth.as_ref())
        .is_none()
    {
        return Err(ServiceError::Message(format!(
            "no saved credential at {}; run `artifact-sync login` before starting the service",
            settings.auth_config.display()
        )));
    }
    let manager_status = platform::status()?;
    if daemon::daemon_is_running().await? {
        let daemon_status = daemon::query_status().await.unwrap_or(None);
        if service_manager_owns_daemon(
            true,
            manager_status.active,
            manager_status.process_id,
            daemon_status.as_ref(),
        ) {
            println!("artifact-sync service is already running.");
            return Ok(());
        }
        return Err(ServiceError::Message(
            "an unmanaged artifact-sync daemon is already running; stop it before starting the installed service".into(),
        ));
    }
    let root = settings
        .publishing_config
        .parent()
        .ok_or_else(|| ServiceError::Message("publishing config has no parent".into()))?;
    let artifact_count = count_publishable_files(root, &settings.publishing_config)?;
    if artifact_count > 0 && !confirm_existing_artifact_uploads(artifact_count, yes, "start")? {
        println!("Service start cancelled; no service files were changed.");
        return Ok(());
    }
    platform::start()?;
    println!("Started artifact-sync service.");
    if artifact_count > 0 {
        println!("Existing artifacts will be reconciled and may upload.");
    }
    Ok(())
}

async fn stop() -> Result<(), ServiceError> {
    if !require_owned_definition()? {
        println!("artifact-sync service is not installed.");
        return Ok(());
    }
    platform::stop()?;
    println!("Stopped artifact-sync service; pending sync work is preserved.");
    Ok(())
}

async fn uninstall() -> Result<(), ServiceError> {
    if !require_owned_definition()? {
        println!("artifact-sync service is not installed; no files were removed.");
        return Ok(());
    }
    platform::uninstall()?;
    let path = platform::definition_path()?;
    fs::remove_file(&path)?;
    platform::reload()?;
    remove_saved_settings_if_owned()?;
    println!("Uninstalled artifact-sync service.");
    println!("Credentials, artifacts, and pending sync state were preserved.");
    Ok(())
}

fn require_owned_definition() -> Result<bool, ServiceError> {
    let path = platform::definition_path()?;
    let owned = owned_definition(&path)?;
    if owned {
        ensure_service_directory(
            path.parent()
                .ok_or_else(|| ServiceError::Message("service definition has no parent".into()))?,
        )?;
    }
    Ok(owned)
}

fn service_manager_owns_daemon(
    definition_is_owned: bool,
    manager_active: bool,
    manager_pid: Option<u32>,
    daemon_status: Option<&daemon::DaemonStatus>,
) -> bool {
    definition_is_owned
        && manager_active
        && daemon_status.is_some_and(|status| manager_pid == Some(status.process_id))
}

fn owned_definition(path: &Path) -> Result<bool, ServiceError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(false),
        Err(error) => return Err(error.into()),
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(ServiceError::Message(format!(
            "service definition path is not a regular file: {}",
            path.display()
        )));
    }
    if metadata.uid() != unsafe { libc::geteuid() } {
        return Err(ServiceError::Message(format!(
            "service definition is not owned by the current user: {}",
            path.display()
        )));
    }
    let contents = fs::read_to_string(path)?;
    if !contents.contains(SERVICE_MARKER) {
        return Err(ServiceError::Message(format!(
            "refusing to overwrite or remove an unmanaged service definition: {}",
            path.display()
        )));
    }
    Ok(true)
}

fn write_managed_definition(path: &Path, contents: &str) -> Result<(), ServiceError> {
    match fs::symlink_metadata(path) {
        Ok(_) => {
            owned_definition(path)?;
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    let parent = path
        .parent()
        .ok_or_else(|| ServiceError::Message("service definition has no parent".into()))?;
    ensure_service_directory(parent)?;
    let counter = TEMP_COUNTER.fetch_add(1, Ordering::Relaxed);
    let file_name = path
        .file_name()
        .ok_or_else(|| ServiceError::Message("service definition has no file name".into()))?
        .to_string_lossy();
    let temporary = parent.join(format!(".{file_name}.{}.{}.tmp", process::id(), counter));
    let write_result = (|| -> Result<(), ServiceError> {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.set_permissions(fs::Permissions::from_mode(0o600))?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        fs::File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if write_result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    write_result
}

fn ensure_service_directory(path: &Path) -> Result<(), ServiceError> {
    let home = dirs::home_dir()
        .ok_or_else(|| ServiceError::Message("home directory unavailable".into()))?;
    let home = fs::canonicalize(home)?;
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()?.join(path)
    };
    let relative = path.strip_prefix(&home).map_err(|_| {
        ServiceError::Message("service definition directory must be inside the user home".into())
    })?;
    let mut current = home;
    for component in relative.components() {
        let std::path::Component::Normal(name) = component else {
            return Err(ServiceError::Message(
                "service definition directory has an unsafe path component".into(),
            ));
        };
        current.push(name);
        match fs::symlink_metadata(&current) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() || !metadata.is_dir() {
                    return Err(ServiceError::Message(format!(
                        "service definition directory contains a symlink or non-directory: {}",
                        current.display()
                    )));
                }
                if metadata.uid() != unsafe { libc::geteuid() }
                    || metadata.permissions().mode() & 0o022 != 0
                {
                    return Err(ServiceError::Message(format!(
                        "service definition directory must be user-owned and not group/world writable: {}",
                        current.display()
                    )));
                }
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                fs::DirBuilder::new().mode(0o700).create(&current)?;
            }
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}

fn saved_settings_path() -> Result<PathBuf, ServiceError> {
    let home = dirs::home_dir()
        .ok_or_else(|| ServiceError::Message("home directory unavailable".into()))?;
    Ok(home.join(".config/artifact-sync/service-settings.json"))
}

fn write_saved_settings(settings: &ServiceSettings) -> Result<(), ServiceError> {
    let path = saved_settings_path()?;
    let parent = path
        .parent()
        .ok_or_else(|| ServiceError::Message("service settings have no parent".into()))?;
    let _directory = open_private_directory(parent)?;
    if path.exists() {
        load_saved_settings()?;
    }
    let saved = SavedServiceSettings {
        managed_by: SERVICE_MARKER.into(),
        version: 1,
        auth_config: settings.auth_config.clone(),
        publishing_config: settings.publishing_config.clone(),
    };
    let contents = serde_json::to_vec_pretty(&saved).map_err(|error| {
        ServiceError::Message(format!("could not encode service settings: {error}"))
    })?;
    let contents = String::from_utf8(contents).map_err(|error| {
        ServiceError::Message(format!("could not encode service settings: {error}"))
    })?;
    write_managed_definition(&path, &contents)
}

fn load_saved_settings() -> Result<ServiceSettings, ServiceError> {
    let path = saved_settings_path()?;
    let _directory = open_private_directory(
        path.parent()
            .ok_or_else(|| ServiceError::Message("service settings have no parent".into()))?,
    )?;
    let metadata = match fs::symlink_metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            return Err(ServiceError::Message(
                "service settings are missing; run `artifact-sync service install` first".into(),
            ));
        }
        Err(error) => return Err(error.into()),
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(ServiceError::Message(
            "service settings path is not a regular file".into(),
        ));
    }
    let contents = fs::read(&path)?;
    let saved: SavedServiceSettings = serde_json::from_slice(&contents).map_err(|error| {
        ServiceError::Message(format!("service settings are malformed: {error}"))
    })?;
    if saved.managed_by != SERVICE_MARKER || saved.version != 1 {
        return Err(ServiceError::Message(
            "service settings are not managed by this version of artifact-sync".into(),
        ));
    }
    Ok(ServiceSettings {
        executable: PathBuf::new(),
        auth_config: saved.auth_config,
        publishing_config: saved.publishing_config,
    })
}

fn remove_saved_settings_if_owned() -> Result<(), ServiceError> {
    let path = saved_settings_path()?;
    match fs::symlink_metadata(&path) {
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error.into()),
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            return Err(ServiceError::Message(
                "refusing to remove service settings that are not a regular file".into(),
            ));
        }
        Ok(_) => {}
    }
    load_saved_settings()?;
    fs::remove_file(path)?;
    Ok(())
}

fn absolute_path(path: &Path) -> Result<PathBuf, ServiceError> {
    Ok(crate::config::canonicalize_missing_tail(path)?)
}

fn count_publishable_files(root: &Path, publishing_config: &Path) -> Result<usize, ServiceError> {
    if !root.is_dir() {
        return Ok(0);
    }
    let mut count = 0;
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_symlink() || !file_type.is_dir() || path == publishing_config {
            continue;
        }
        let slug = entry.file_name();
        if !slug
            .to_str()
            .is_some_and(crate::state::is_valid_artifact_slug)
        {
            continue;
        }
        count_files_recursive(root, &path, publishing_config, &mut count)?;
    }
    Ok(count)
}

fn count_files_recursive(
    root: &Path,
    directory: &Path,
    publishing_config: &Path,
    count: &mut usize,
) -> Result<(), ServiceError> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_symlink()
            || path == publishing_config
            || path.strip_prefix(root).ok().is_some_and(|relative| {
                relative
                    .components()
                    .any(|part| part.as_os_str() == ".artifact-sync")
            })
        {
            continue;
        }
        if file_type.is_dir() {
            count_files_recursive(root, &path, publishing_config, count)?;
        } else if file_type.is_file() {
            *count += 1;
        }
    }
    Ok(())
}

fn confirm_existing_artifact_uploads(
    artifact_count: usize,
    yes: bool,
    operation: &str,
) -> Result<bool, ServiceError> {
    if artifact_count == 0 || yes {
        return Ok(true);
    }
    confirm_existing_artifact_uploads_interactive(
        artifact_count,
        io::stdin().is_terminal(),
        operation,
    )
}

fn confirm_existing_artifact_uploads_interactive(
    artifact_count: usize,
    interactive: bool,
    operation: &str,
) -> Result<bool, ServiceError> {
    if artifact_count == 0 {
        return Ok(true);
    }
    if !interactive {
        return Err(ServiceError::Message(format!(
            "{artifact_count} existing artifact(s) may upload when the service starts; rerun with `artifact-sync service {operation} --yes` to confirm",
        )));
    }
    print!(
        "The daemon may upload {artifact_count} existing artifact(s) at startup. Install and start the service? [y/N] "
    );
    io::stdout().flush()?;
    let mut answer = String::new();
    io::stdin().read_line(&mut answer)?;
    Ok(matches!(
        answer.trim().to_ascii_lowercase().as_str(),
        "y" | "yes"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::symlink;

    #[test]
    fn definition_write_is_private_atomic_and_only_replaces_owned_file() {
        let temp = tempfile::TempDir::new_in(dirs::home_dir().unwrap()).unwrap();
        fs::set_permissions(temp.path(), fs::Permissions::from_mode(0o700)).unwrap();
        let path = temp.path().join("service.conf");
        let contents = format!("# {SERVICE_MARKER}\nExecStart=artifact-sync\n");
        write_managed_definition(&path, &contents).unwrap();
        assert_eq!(
            fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), contents);

        write_managed_definition(&path, &format!("# {SERVICE_MARKER}\nUpdated=true\n")).unwrap();
        assert!(fs::read_to_string(&path).unwrap().contains("Updated=true"));
    }

    #[test]
    fn definition_writer_refuses_symlinks_and_unmanaged_files() {
        let temp = tempfile::TempDir::new_in(dirs::home_dir().unwrap()).unwrap();
        let victim = temp.path().join("victim");
        let path = temp.path().join("service.conf");
        fs::write(&victim, "preserve me").unwrap();
        symlink(&victim, &path).unwrap();
        assert!(write_managed_definition(&path, "replacement").is_err());
        assert_eq!(fs::read_to_string(&victim).unwrap(), "preserve me");

        fs::remove_file(&path).unwrap();
        symlink(temp.path().join("missing"), &path).unwrap();
        assert!(write_managed_definition(&path, "replacement").is_err());
        assert!(
            fs::symlink_metadata(&path)
                .unwrap()
                .file_type()
                .is_symlink()
        );

        fs::remove_file(&path).unwrap();
        fs::write(&path, "not managed").unwrap();
        assert!(write_managed_definition(&path, "replacement").is_err());
        assert_eq!(fs::read_to_string(&path).unwrap(), "not managed");
    }

    #[test]
    fn install_preflight_counts_only_files_the_daemon_would_publish() {
        let temp = tempfile::TempDir::new_in(dirs::home_dir().unwrap()).unwrap();
        let root = temp.path().join("artifacts");
        fs::create_dir_all(root.join(".artifact-sync")).unwrap();
        fs::create_dir_all(root.join("valid/nested")).unwrap();
        fs::create_dir_all(root.join("BadSlug")).unwrap();
        fs::write(root.join("loose-report.json"), "ignored").unwrap();
        fs::write(root.join("valid/nested/report.json"), "{} ").unwrap();
        fs::write(root.join("BadSlug/private.txt"), "ignored").unwrap();
        fs::write(root.join("config.json"), "{}").unwrap();
        fs::write(root.join(".artifact-sync/state"), "local").unwrap();
        let publishing = root.join("config.json");
        assert_eq!(count_publishable_files(&root, &publishing).unwrap(), 1);
    }

    #[test]
    fn upload_confirmation_requires_yes_when_headless_and_artifacts_exist() {
        let error = confirm_existing_artifact_uploads_interactive(2, false, "install").unwrap_err();
        assert!(error.to_string().contains("service install --yes"));
        let error = confirm_existing_artifact_uploads_interactive(2, false, "start").unwrap_err();
        assert!(error.to_string().contains("service start --yes"));
        assert!(confirm_existing_artifact_uploads_interactive(0, false, "start").unwrap());
    }

    #[test]
    fn managed_service_ownership_requires_a_matching_native_manager_pid() {
        let status = daemon::DaemonStatus {
            publishing_state: daemon::PublishingState::Ready,
            process_id: 42,
            artifact_root: "/home/user/artifacts".into(),
            team: Some("w3dev".into()),
            identity_verified: true,
            credential_source: Some("auth file".into()),
            pending_count: 0,
        };
        assert!(service_manager_owns_daemon(
            true,
            true,
            Some(42),
            Some(&status)
        ));
        assert!(!service_manager_owns_daemon(
            true,
            true,
            Some(41),
            Some(&status)
        ));
        assert!(!service_manager_owns_daemon(
            true,
            false,
            Some(42),
            Some(&status)
        ));
        assert!(!service_manager_owns_daemon(
            false,
            true,
            Some(42),
            Some(&status)
        ));
        assert!(!service_manager_owns_daemon(true, true, Some(42), None));
    }
}
